# .graphqlrc.yml
schema:
  - "./types/generated/admin.schema.json"
  # - "./node_modules/@shopify/hydrogen-react/storefront.schema.json"
# documents: "./**/*-storefront.ts"
documents: "./**/*-graphql.ts"
