/**
 * This file is auto generated from a GraphQl introspection query
 */

import { CountryCode } from './types/admin.types';

/**
 * Les noms complets des pays présent dans l'enum CountryCode présente dans ./admin.types.d.ts
 */
export const countryNames: Record<CountryCode, string> = {
  [CountryCode.Af]: `Afghanistan.`,
  [CountryCode.Ax]: `Åland Islands.`,
  [CountryCode.Al]: `Albania.`,
  [CountryCode.Dz]: `Algeria.`,
  [CountryCode.Ad]: `Andorra.`,
  [CountryCode.Ao]: `Angola.`,
  [CountryCode.Ai]: `Anguilla.`,
  [CountryCode.Ag]: `Antigua & Barbuda.`,
  [CountryCode.Ar]: `Argentina.`,
  [CountryCode.Am]: `Armenia.`,
  [CountryCode.Aw]: `Aruba.`,
  [CountryCode.Ac]: `Ascension Island.`,
  [CountryCode.Au]: `Australia.`,
  [CountryCode.At]: `Austria.`,
  [CountryCode.Az]: `Azerbaijan.`,
  [CountryCode.Bs]: `Bahamas.`,
  [CountryCode.Bh]: `Bahrain.`,
  [CountryCode.Bd]: `Bangladesh.`,
  [CountryCode.Bb]: `Barbados.`,
  [CountryCode.By]: `Belarus.`,
  [CountryCode.Be]: `Belgium.`,
  [CountryCode.Bz]: `Belize.`,
  [CountryCode.Bj]: `Benin.`,
  [CountryCode.Bm]: `Bermuda.`,
  [CountryCode.Bt]: `Bhutan.`,
  [CountryCode.Bo]: `Bolivia.`,
  [CountryCode.Ba]: `Bosnia & Herzegovina.`,
  [CountryCode.Bw]: `Botswana.`,
  [CountryCode.Bv]: `Bouvet Island.`,
  [CountryCode.Br]: `Brazil.`,
  [CountryCode.Io]: `British Indian Ocean Territory.`,
  [CountryCode.Bn]: `Brunei.`,
  [CountryCode.Bg]: `Bulgaria.`,
  [CountryCode.Bf]: `Burkina Faso.`,
  [CountryCode.Bi]: `Burundi.`,
  [CountryCode.Kh]: `Cambodia.`,
  [CountryCode.Ca]: `Canada.`,
  [CountryCode.Cv]: `Cape Verde.`,
  [CountryCode.Bq]: `Caribbean Netherlands.`,
  [CountryCode.Ky]: `Cayman Islands.`,
  [CountryCode.Cf]: `Central African Republic.`,
  [CountryCode.Td]: `Chad.`,
  [CountryCode.Cl]: `Chile.`,
  [CountryCode.Cn]: `China.`,
  [CountryCode.Cx]: `Christmas Island.`,
  [CountryCode.Cc]: `Cocos (Keeling) Islands.`,
  [CountryCode.Co]: `Colombia.`,
  [CountryCode.Km]: `Comoros.`,
  [CountryCode.Cg]: `Congo - Brazzaville.`,
  [CountryCode.Cd]: `Congo - Kinshasa.`,
  [CountryCode.Ck]: `Cook Islands.`,
  [CountryCode.Cr]: `Costa Rica.`,
  [CountryCode.Hr]: `Croatia.`,
  [CountryCode.Cu]: `Cuba.`,
  [CountryCode.Cw]: `Curaçao.`,
  [CountryCode.Cy]: `Cyprus.`,
  [CountryCode.Cz]: `Czechia.`,
  [CountryCode.Ci]: `Côte d’Ivoire.`,
  [CountryCode.Dk]: `Denmark.`,
  [CountryCode.Dj]: `Djibouti.`,
  [CountryCode.Dm]: `Dominica.`,
  [CountryCode.Do]: `Dominican Republic.`,
  [CountryCode.Ec]: `Ecuador.`,
  [CountryCode.Eg]: `Egypt.`,
  [CountryCode.Sv]: `El Salvador.`,
  [CountryCode.Gq]: `Equatorial Guinea.`,
  [CountryCode.Er]: `Eritrea.`,
  [CountryCode.Ee]: `Estonia.`,
  [CountryCode.Sz]: `Eswatini.`,
  [CountryCode.Et]: `Ethiopia.`,
  [CountryCode.Fk]: `Falkland Islands.`,
  [CountryCode.Fo]: `Faroe Islands.`,
  [CountryCode.Fj]: `Fiji.`,
  [CountryCode.Fi]: `Finland.`,
  [CountryCode.Fr]: `France.`,
  [CountryCode.Gf]: `French Guiana.`,
  [CountryCode.Pf]: `French Polynesia.`,
  [CountryCode.Tf]: `French Southern Territories.`,
  [CountryCode.Ga]: `Gabon.`,
  [CountryCode.Gm]: `Gambia.`,
  [CountryCode.Ge]: `Georgia.`,
  [CountryCode.De]: `Germany.`,
  [CountryCode.Gh]: `Ghana.`,
  [CountryCode.Gi]: `Gibraltar.`,
  [CountryCode.Gr]: `Greece.`,
  [CountryCode.Gl]: `Greenland.`,
  [CountryCode.Gd]: `Grenada.`,
  [CountryCode.Gp]: `Guadeloupe.`,
  [CountryCode.Gt]: `Guatemala.`,
  [CountryCode.Gg]: `Guernsey.`,
  [CountryCode.Gn]: `Guinea.`,
  [CountryCode.Gw]: `Guinea-Bissau.`,
  [CountryCode.Gy]: `Guyana.`,
  [CountryCode.Ht]: `Haiti.`,
  [CountryCode.Hm]: `Heard & McDonald Islands.`,
  [CountryCode.Va]: `Vatican City.`,
  [CountryCode.Hn]: `Honduras.`,
  [CountryCode.Hk]: `Hong Kong SAR.`,
  [CountryCode.Hu]: `Hungary.`,
  [CountryCode.Is]: `Iceland.`,
  [CountryCode.In]: `India.`,
  [CountryCode.Id]: `Indonesia.`,
  [CountryCode.Ir]: `Iran.`,
  [CountryCode.Iq]: `Iraq.`,
  [CountryCode.Ie]: `Ireland.`,
  [CountryCode.Im]: `Isle of Man.`,
  [CountryCode.Il]: `Israel.`,
  [CountryCode.It]: `Italy.`,
  [CountryCode.Jm]: `Jamaica.`,
  [CountryCode.Jp]: `Japan.`,
  [CountryCode.Je]: `Jersey.`,
  [CountryCode.Jo]: `Jordan.`,
  [CountryCode.Kz]: `Kazakhstan.`,
  [CountryCode.Ke]: `Kenya.`,
  [CountryCode.Ki]: `Kiribati.`,
  [CountryCode.Kp]: `North Korea.`,
  [CountryCode.Xk]: `Kosovo.`,
  [CountryCode.Kw]: `Kuwait.`,
  [CountryCode.Kg]: `Kyrgyzstan.`,
  [CountryCode.La]: `Laos.`,
  [CountryCode.Lv]: `Latvia.`,
  [CountryCode.Lb]: `Lebanon.`,
  [CountryCode.Ls]: `Lesotho.`,
  [CountryCode.Lr]: `Liberia.`,
  [CountryCode.Ly]: `Libya.`,
  [CountryCode.Li]: `Liechtenstein.`,
  [CountryCode.Lt]: `Lithuania.`,
  [CountryCode.Lu]: `Luxembourg.`,
  [CountryCode.Mo]: `Macao SAR.`,
  [CountryCode.Mg]: `Madagascar.`,
  [CountryCode.Mw]: `Malawi.`,
  [CountryCode.My]: `Malaysia.`,
  [CountryCode.Mv]: `Maldives.`,
  [CountryCode.Ml]: `Mali.`,
  [CountryCode.Mt]: `Malta.`,
  [CountryCode.Mq]: `Martinique.`,
  [CountryCode.Mr]: `Mauritania.`,
  [CountryCode.Mu]: `Mauritius.`,
  [CountryCode.Yt]: `Mayotte.`,
  [CountryCode.Mx]: `Mexico.`,
  [CountryCode.Md]: `Moldova.`,
  [CountryCode.Mc]: `Monaco.`,
  [CountryCode.Mn]: `Mongolia.`,
  [CountryCode.Me]: `Montenegro.`,
  [CountryCode.Ms]: `Montserrat.`,
  [CountryCode.Ma]: `Morocco.`,
  [CountryCode.Mz]: `Mozambique.`,
  [CountryCode.Mm]: `Myanmar (Burma).`,
  [CountryCode.Na]: `Namibia.`,
  [CountryCode.Nr]: `Nauru.`,
  [CountryCode.Np]: `Nepal.`,
  [CountryCode.Nl]: `Netherlands.`,
  [CountryCode.An]: `Netherlands Antilles.`,
  [CountryCode.Nc]: `New Caledonia.`,
  [CountryCode.Nz]: `New Zealand.`,
  [CountryCode.Ni]: `Nicaragua.`,
  [CountryCode.Ne]: `Niger.`,
  [CountryCode.Ng]: `Nigeria.`,
  [CountryCode.Nu]: `Niue.`,
  [CountryCode.Nf]: `Norfolk Island.`,
  [CountryCode.Mk]: `North Macedonia.`,
  [CountryCode.No]: `Norway.`,
  [CountryCode.Om]: `Oman.`,
  [CountryCode.Pk]: `Pakistan.`,
  [CountryCode.Ps]: `Palestinian Territories.`,
  [CountryCode.Pa]: `Panama.`,
  [CountryCode.Pg]: `Papua New Guinea.`,
  [CountryCode.Py]: `Paraguay.`,
  [CountryCode.Pe]: `Peru.`,
  [CountryCode.Ph]: `Philippines.`,
  [CountryCode.Pn]: `Pitcairn Islands.`,
  [CountryCode.Pl]: `Poland.`,
  [CountryCode.Pt]: `Portugal.`,
  [CountryCode.Qa]: `Qatar.`,
  [CountryCode.Cm]: `Cameroon.`,
  [CountryCode.Re]: `Réunion.`,
  [CountryCode.Ro]: `Romania.`,
  [CountryCode.Ru]: `Russia.`,
  [CountryCode.Rw]: `Rwanda.`,
  [CountryCode.Bl]: `St. Barthélemy.`,
  [CountryCode.Sh]: `St. Helena.`,
  [CountryCode.Kn]: `St. Kitts & Nevis.`,
  [CountryCode.Lc]: `St. Lucia.`,
  [CountryCode.Mf]: `St. Martin.`,
  [CountryCode.Pm]: `St. Pierre & Miquelon.`,
  [CountryCode.Ws]: `Samoa.`,
  [CountryCode.Sm]: `San Marino.`,
  [CountryCode.St]: `São Tomé & Príncipe.`,
  [CountryCode.Sa]: `Saudi Arabia.`,
  [CountryCode.Sn]: `Senegal.`,
  [CountryCode.Rs]: `Serbia.`,
  [CountryCode.Sc]: `Seychelles.`,
  [CountryCode.Sl]: `Sierra Leone.`,
  [CountryCode.Sg]: `Singapore.`,
  [CountryCode.Sx]: `Sint Maarten.`,
  [CountryCode.Sk]: `Slovakia.`,
  [CountryCode.Si]: `Slovenia.`,
  [CountryCode.Sb]: `Solomon Islands.`,
  [CountryCode.So]: `Somalia.`,
  [CountryCode.Za]: `South Africa.`,
  [CountryCode.Gs]: `South Georgia & South Sandwich Islands.`,
  [CountryCode.Kr]: `South Korea.`,
  [CountryCode.Ss]: `South Sudan.`,
  [CountryCode.Es]: `Spain.`,
  [CountryCode.Lk]: `Sri Lanka.`,
  [CountryCode.Vc]: `St. Vincent & Grenadines.`,
  [CountryCode.Sd]: `Sudan.`,
  [CountryCode.Sr]: `Suriname.`,
  [CountryCode.Sj]: `Svalbard & Jan Mayen.`,
  [CountryCode.Se]: `Sweden.`,
  [CountryCode.Ch]: `Switzerland.`,
  [CountryCode.Sy]: `Syria.`,
  [CountryCode.Tw]: `Taiwan.`,
  [CountryCode.Tj]: `Tajikistan.`,
  [CountryCode.Tz]: `Tanzania.`,
  [CountryCode.Th]: `Thailand.`,
  [CountryCode.Tl]: `Timor-Leste.`,
  [CountryCode.Tg]: `Togo.`,
  [CountryCode.Tk]: `Tokelau.`,
  [CountryCode.To]: `Tonga.`,
  [CountryCode.Tt]: `Trinidad & Tobago.`,
  [CountryCode.Ta]: `Tristan da Cunha.`,
  [CountryCode.Tn]: `Tunisia.`,
  [CountryCode.Tr]: `Türkiye.`,
  [CountryCode.Tm]: `Turkmenistan.`,
  [CountryCode.Tc]: `Turks & Caicos Islands.`,
  [CountryCode.Tv]: `Tuvalu.`,
  [CountryCode.Ug]: `Uganda.`,
  [CountryCode.Ua]: `Ukraine.`,
  [CountryCode.Ae]: `United Arab Emirates.`,
  [CountryCode.Gb]: `United Kingdom.`,
  [CountryCode.Us]: `United States.`,
  [CountryCode.Um]: `U.S. Outlying Islands.`,
  [CountryCode.Uy]: `Uruguay.`,
  [CountryCode.Uz]: `Uzbekistan.`,
  [CountryCode.Vu]: `Vanuatu.`,
  [CountryCode.Ve]: `Venezuela.`,
  [CountryCode.Vn]: `Vietnam.`,
  [CountryCode.Vg]: `British Virgin Islands.`,
  [CountryCode.Wf]: `Wallis & Futuna.`,
  [CountryCode.Eh]: `Western Sahara.`,
  [CountryCode.Ye]: `Yemen.`,
  [CountryCode.Zm]: `Zambia.`,
  [CountryCode.Zw]: `Zimbabwe.`,
  [CountryCode.Zz]: `Unknown Region.`
} as const;
