import { GraphQlResource } from '../types/GraphQl';
import { ResourceMetafieldsSyncTableDefinition } from '../types/Metafields';
import { MetafieldOwnerType } from '../types/admin.types';

export const RESOURCE_METAFIELDS_SYNC_TABLE_DEFINITIONS: ResourceMetafieldsSyncTableDefinition[] = [
  {
    key: GraphQlResource.Article,
    metafieldOwnerType: MetafieldOwnerType.Article,
    display: 'Article',
    metafieldsSettingsUrlPart: 'article',
    editMetafieldUrlPart: 'articles',
    ownerRestUrlPart: 'articles',
    syncTableGraphQlQueryOperation: 'articles', // TODO: no graphQL here
    graphQlQueryOperation: 'article', // TODO: no graphQL here
  },
  {
    key: GraphQlResource.Blog,
    metafieldOwnerType: MetafieldOwnerType.Blog,
    display: 'Blog',
    metafieldsSettingsUrlPart: 'blog',
    editMetafieldUrlPart: 'blogs',
    ownerRestUrlPart: 'blogs',
    syncTableGraphQlQueryOperation: 'blogs', // TODO: no graphQL here
    graphQlQueryOperation: 'blog', // TODO: no graphQL here
    storeFront: true,
  },
  {
    key: GraphQlResource.Collection,
    metafieldOwnerType: MetafieldOwnerType.Collection,
    display: 'Collection',
    metafieldsSettingsUrlPart: 'collection',
    editMetafieldUrlPart: 'collections',
    ownerRestUrlPart: 'collections',
    syncTableGraphQlQueryOperation: 'collections',
    graphQlQueryOperation: 'collection',
  },
  // {
  //   key: 'smart_collection',
  //   metafieldOwnerType: 'LOL',
  //   display: 'Smart Collection',
  //   adminUrlPart: 'collection',
  //   adminEntryUrlPart: 'collections',
  //   graphQlQueryOperation: 'collections',
  // },
  {
    key: GraphQlResource.Customer,
    metafieldOwnerType: MetafieldOwnerType.Customer,
    display: 'Customer',
    metafieldsSettingsUrlPart: 'customer',
    editMetafieldUrlPart: 'customers',
    ownerRestUrlPart: 'customers',
    syncTableGraphQlQueryOperation: 'customers',
    graphQlQueryOperation: 'customer',
  },
  // TODO: maybe add suppoort for draft orders later
  // {
  //   key: 'draft_order',
  //   metafieldOwnerType: MetafieldOwnerType.Draftorder,
  //   display: 'Draft Order',
  //   adminUrlPart: 'draftOrder',
  //   adminEntryUrlPart: 'draftOrders',
  //   graphQlQueryOperation: 'draftOrders',
  // },
  {
    key: GraphQlResource.Location,
    metafieldOwnerType: MetafieldOwnerType.Location,
    display: 'Location',
    metafieldsSettingsUrlPart: 'location',
    editMetafieldUrlPart: 'locations',
    ownerRestUrlPart: 'locations',
    syncTableGraphQlQueryOperation: 'locations',
    graphQlQueryOperation: 'location',
  },
  {
    key: GraphQlResource.Order,
    metafieldOwnerType: MetafieldOwnerType.Order,
    display: 'Order',
    metafieldsSettingsUrlPart: 'order',
    editMetafieldUrlPart: 'orders',
    ownerRestUrlPart: 'orders',
    syncTableGraphQlQueryOperation: 'orders',
    graphQlQueryOperation: 'order',
  },
  {
    key: GraphQlResource.Page,
    metafieldOwnerType: MetafieldOwnerType.Page,
    display: 'Page',
    metafieldsSettingsUrlPart: 'page',
    editMetafieldUrlPart: 'pages',
    ownerRestUrlPart: 'pages',
    syncTableGraphQlQueryOperation: 'pages', // TODO: no graphQL here
    graphQlQueryOperation: 'page', // TODO: no graphQL here
    storeFront: true,
  },
  {
    key: GraphQlResource.Product,
    metafieldOwnerType: MetafieldOwnerType.Product,
    display: 'Product',
    metafieldsSettingsUrlPart: 'product',
    editMetafieldUrlPart: 'products',
    ownerRestUrlPart: 'products',
    syncTableGraphQlQueryOperation: 'products',
    graphQlQueryOperation: 'product',
    storeFront: true,
  },
  // {
  //   key: 'product_image',
  //   metafieldOwnerType: 'LOL',
  //   display: 'Product Image',
  //   adminUrlPart: 'article',
  //   adminEntryUrlPart: 'articles',
  //   graphQlQueryOperation: 'articles',
  // },
  {
    key: GraphQlResource.ProductVariant,
    metafieldOwnerType: MetafieldOwnerType.Productvariant,
    display: 'Product Variant',
    metafieldsSettingsUrlPart: 'productVariant',
    editMetafieldUrlPart: 'productVariants',
    ownerRestUrlPart: 'productVariants',
    syncTableGraphQlQueryOperation: 'productVariants',
    graphQlQueryOperation: 'productVariant',
    // storeFront: true,
  },
  {
    key: GraphQlResource.Shop,
    metafieldOwnerType: MetafieldOwnerType.Shop,
    display: 'Shop',
    metafieldsSettingsUrlPart: 'shop',
    editMetafieldUrlPart: 'shop',
    ownerRestUrlPart: 'shop',
    syncTableGraphQlQueryOperation: 'shop',
    graphQlQueryOperation: 'shop',
  },
];
