import * as coda from '@codahq/packs-sdk';
import {
  addressAddress1,
  addressAddress2,
  addressCityProp,
  addressCountryCodeProp,
  addressCountryNameProp,
  addressCountryProp,
  addressLatitudeProp,
  addressLongitudeProp,
  addressPersonCompanyProp,
  addressPersonFirstNameProp,
  addressPersonFullNameProp,
  addressPersonLastNameProp,
  addressPhoneProp,
  addressProvinceCodeProp,
  addressProvinceProp,
  addressZipProp,
} from './AddressSchema';

export const HarmonizedSystemCodeSchema = coda.makeObjectSchema({
  properties: {
    display: {
      type: coda.ValueType.String,
      description: 'Formatted display name of the address.',
    },
    address1: addressAddress1,
    address2: addressAddress2,
    city: addressCityProp,
    company: addressPersonCompanyProp,
    country: addressCountryProp,
    country_code: addressCountryCodeProp,
    country_name: addressCountryNameProp,
    first_name: addressPersonFirstNameProp,
    last_name: addressPersonLastNameProp,
    name: addressPersonFullNameProp,
    latitude: addressLongitudeProp,
    longitude: addressLatitudeProp,
    phone: addressPhoneProp,
    province: addressProvinceProp,
    province_code: addressProvinceCodeProp,
    zip: addressZipProp,
  },
  displayProperty: 'display',
});
