/**
 * This file is autogenerated from SyncTable schemas present in the pack.
 * You should't need to manually edit.
 *
 * Identities: Article, Blog, Collect, Collection, Customer, DraftOrder, File, InventoryItem, InventoryLevel, Location, Metafield, MetafieldDefinition, Metaobject, Order, OrderLineItem, OrderTransaction, Page, Product, ProductVariant, Redirect, Shop
 * Last generated: 2024-04-22T08:24:41.435Z
 *
 */

type UsedDisplayProperties = 'title' | 'id' | 'name' | 'display' | 'unique_id' | 'label' | 'handle' | 'path';

export type FormatRowReferenceFn<T, displayPropT extends string = never> = (
  id: T,
  displayProp?: string
) => {
  /** The row idProperty. */
  id: T;
} & {
  /** For the row displayProperty. Could be name, title… anything */
  [k in displayPropT]: string;
};

export interface BaseRow extends Record<string, any> {
  id: number | string;
}

export type RowWithMetafields<RowT extends BaseRow> = RowT & {
  [key: string]: any;
};

/**
 * Coda Row Interface for Articles Sync Table
 */
export interface ArticleRow extends BaseRow {
  id: number;
  admin_graphql_api_id?: string;
  admin_url?: string;
  author?: string;
  blog_id?: number;
  blog?: {
    id: number;
    title: string;
  };
  body?: string;
  body_html?: string;
  created_at?: string | number | Date;
  handle?: string;
  image_url?: string;
  image_alt_text?: string;
  published?: boolean;
  published_at?: string | number | Date;
  summary?: string;
  summary_html?: string;
  tags?: string;
  template_suffix?: string;
  title: string;
  updated_at?: string | number | Date;
  user_id?: number;
}

/**
 * Coda Row Interface for Blogs Sync Table
 */
export interface BlogRow extends BaseRow {
  id: number;
  admin_url?: string;
  admin_graphql_api_id?: string;
  commentable?: string;
  created_at?: string | number | Date;
  handle?: string;
  tags?: string;
  template_suffix?: string;
  title: string;
  updated_at?: string | number | Date;
}

/**
 * Coda Row Interface for Collects Sync Table
 */
export interface CollectRow extends BaseRow {
  id: number;
  collection_id?: number;
  collection?: {
    id: number;
    title: string;
  };
  created_at?: string | number | Date;
  position?: number;
  product_id?: number;
  product?: {
    id: number;
    title: string;
  };
  updated_at?: string | number | Date;
}

/**
 * Coda Row Interface for Collections Sync Table
 */
export interface CollectionRow extends BaseRow {
  admin_graphql_api_id?: string;
  admin_url?: string;
  id: number;
  body?: string;
  body_html?: string;
  handle?: string;
  image_url?: string;
  image_alt_text?: string;
  published?: boolean;
  published_at?: string | number | Date;
  published_scope?: string;
  rules?: {
    column?: string;
    relation?: string;
    condition?: string;
  }[];
  ruleSet?: {
    display?: string;
    rules?: {
      column?: string;
      condition?: string;
      relation?: string;
    }[];
    appliedDisjunctively?: boolean;
  };
  disjunctive?: boolean;
  sort_order?: string;
  template_suffix?: string;
  title: string;
  updated_at?: string | number | Date;
}

/**
 * Coda Row Interface for DraftOrders Sync Table
 */
export interface DraftOrderRow extends BaseRow {
  admin_url?: string;
  applied_discount?: {
    allocation_method?: string;
    amount?: number;
    code?: string;
    description?: string;
    target_selection?: string;
    target_type?: string;
    title?: string;
    type?: string;
    value?: number;
    value_type?: string;
  };
  billing_address?: {
    display?: string;
    address1?: string;
    address2?: string;
    city?: string;
    company?: string;
    country?: string;
    country_code?: string;
    country_name?: string;
    first_name?: string;
    last_name?: string;
    name?: string;
    latitude?: string;
    longitude?: string;
    phone?: string;
    province?: string;
    province_code?: string;
    zip?: string;
  };
  completed_at?: string | number | Date;
  created_at?: string | number | Date;
  currency?: string;
  customer?: {
    id: number;
    display: string;
  };
  email?: string;
  admin_graphql_api_id?: string;
  id: number;
  invoice_sent_at?: string | number | Date;
  invoice_url?: string;
  line_items?: {
    id: number;
    attributed_staffs?: {
      id?: string;
      quantity?: number;
    }[];
    custom?: boolean;
    fulfillable_quantity?: number;
    fulfillment_service?: string;
    fulfillment_status?: string;
    grams?: number;
    price?: number;
    product_id?: number;
    quantity?: number;
    requires_shipping?: boolean;
    sku?: string;
    title?: string;
    variant_id?: number;
    variant_title?: string;
    vendor?: string;
    name: string;
    gift_card?: boolean;
    properties?: {
      name?: string;
      value?: string;
    }[];
    taxable?: boolean;
    tax_lines?: {
      title?: string;
      price?: number;
      rate?: number;
      channel_liable?: boolean;
    }[];
    tip_payment_gateway?: string;
    tip_payment_method?: string;
    total_discount?: number;
    discount_allocations?: {
      amount?: number;
      discount_application_index?: number;
    }[];
    duties?: {
      id: number;
      tax_lines?: {
        title?: string;
        price?: number;
        rate?: number;
        channel_liable?: boolean;
      }[];
      country_code_of_origin?: string;
      harmonized_system_code?: string;
    }[];
    product_exists?: boolean;
    variant_inventory_management?: string;
  }[];
  name: string;
  note_attributes?: {
    name?: string;
    value?: string;
  }[];
  note?: string;
  order_id?: number;
  order?: {
    id: number;
    name: string;
  };
  payment_terms?: {
    amount?: number;
    currency?: string;
    payment_terms_name?: string;
    payment_terms_type?: string;
    due_in_days?: number;
    payment_schedules?: {
      amount?: number;
      currency?: string;
      issued_at?: string | number | Date;
      due_at?: string | number | Date;
      completed_at?: string | number | Date;
      expected_payment_method?: string;
    }[];
  };
  shipping_address?: {
    display?: string;
    address1?: string;
    address2?: string;
    city?: string;
    company?: string;
    country?: string;
    country_code?: string;
    country_name?: string;
    first_name?: string;
    last_name?: string;
    name?: string;
    latitude?: string;
    longitude?: string;
    phone?: string;
    province?: string;
    province_code?: string;
    zip?: string;
  };
  shipping_line?: {
    id: number;
    code?: string;
    discounted_price?: number;
    price?: number;
    source?: string;
    title?: string;
    tax_lines?: {
      title?: string;
      price?: number;
      rate?: number;
      channel_liable?: boolean;
    }[];
    carrier_identifier?: string;
    requested_fulfillment_service_id?: string;
  };
  status?: string;
  subtotal_price?: number;
  tags?: string;
  tax_exempt?: boolean;
  tax_exemptions?: string[];
  tax_lines?: {
    title?: string;
    price?: number;
    rate?: number;
    channel_liable?: boolean;
  }[];
  taxes_included?: boolean;
  total_price?: number;
  total_tax?: number;
  updated_at?: string | number | Date;
}

/**
 * Coda Row Interface for Customers Sync Table
 */
export interface CustomerRow extends BaseRow {
  admin_url?: string;
  admin_graphql_api_id?: string;
  id: number;
  display: string;
  addresses?: {
    display?: string;
    address1?: string;
    address2?: string;
    city?: string;
    company?: string;
    country?: string;
    country_code?: string;
    country_name?: string;
    first_name?: string;
    last_name?: string;
    name?: string;
    latitude?: string;
    longitude?: string;
    phone?: string;
    province?: string;
    province_code?: string;
    zip?: string;
    id: number;
    default?: boolean;
  }[];
  created_at?: string | number | Date;
  default_address?: {
    display?: string;
    address1?: string;
    address2?: string;
    city?: string;
    company?: string;
    country?: string;
    country_code?: string;
    country_name?: string;
    first_name?: string;
    last_name?: string;
    name?: string;
    latitude?: string;
    longitude?: string;
    phone?: string;
    province?: string;
    province_code?: string;
    zip?: string;
    id: number;
    default?: boolean;
  };
  email?: string;
  accepts_email_marketing?: boolean;
  accepts_sms_marketing?: boolean;
  first_name?: string;
  last_name?: string;
  last_order_id?: number;
  last_order_name?: string;
  multipass_identifier?: string;
  note?: string;
  orders_count?: number;
  phone?: string;
  state?: string;
  tags?: string;
  tax_exempt?: boolean;
  tax_exemptions?: string[];
  total_spent?: number;
  updated_at?: string | number | Date;
  verified_email?: boolean;
}

/**
 * Coda Row Interface for Files Sync Table
 */
export interface FileRow extends BaseRow {
  name: string;
  id: string;
  alt?: string;
  createdAt?: string | number | Date;
  updatedAt?: string | number | Date;
  preview?: string;
  mimeType?: string;
  fileSize?: number;
  url?: string;
  width?: number;
  height?: number;
  duration?: number;
  type?: string;
}

/**
 * Coda Row Interface for InventoryItems Sync Table
 */
export interface InventoryItemRow extends BaseRow {
  admin_graphql_api_id?: string;
  id: number;
  inventory_history_url?: string;
  cost?: number;
  country_code_of_origin?: string;
  harmonized_system_code?: string;
  province_code_of_origin?: string;
  updated_at?: string | number | Date;
  created_at?: string | number | Date;
  tracked?: boolean;
  requires_shipping?: boolean;
  variant?: {
    id: number;
    title: string;
  };
  variant_id?: number;
}

/**
 * Coda Row Interface for InventoryLevels Sync Table
 */
export interface InventoryLevelRow extends BaseRow {
  admin_graphql_api_id?: string;
  available?: number;
  inventory_item_id?: number;
  inventory_item?: {
    id: number;
  };
  location_id?: number;
  location?: {
    id: number;
    name: string;
  };
  id: string;
  updated_at?: string | number | Date;
  inventory_history_url?: string;
}

/**
 * Coda Row Interface for Locations Sync Table
 */
export interface LocationRow extends BaseRow {
  id: number;
  active?: boolean;
  address1?: string;
  address2?: string;
  city?: string;
  country?: string;
  country_code?: string;
  name: string;
  phone?: string;
  province?: string;
  province_code?: string;
  zip?: string;
  admin_url?: string;
  stock_url?: string;
  admin_graphql_api_id?: string;
  local_pickup_settings?: {
    instructions?: string;
    pickupTime?: string;
  };
  ships_inventory?: boolean;
  fulfills_online_orders?: boolean;
  fulfillment_service?: string;
  has_active_inventory?: boolean;
}

/**
 * Coda Row Interface for Metafields Sync Table
 */
export interface MetafieldRow extends BaseRow {
  admin_graphql_api_id?: string;
  id: number;
  label: string;
  admin_url?: string;
  key?: string;
  namespace?: string;
  owner_id: number;
  owner_type: string;
  rawValue?: string;
  type: string;
  created_at?: string | number | Date;
  updated_at?: string | number | Date;
  editCollectionReference?: {
    id: number;
    title: string;
  };
  editCollectionReferenceList?: {
    id: number;
    title: string;
  }[];
  editFileReference?: {
    id: string;
    name: string;
  };
  editFileReferenceList?: {
    id: string;
    name: string;
  }[];
  editPageReference?: {
    id: number;
    title: string;
  };
  editPageReferenceList?: {
    id: number;
    title: string;
  }[];
  editProductReference?: {
    id: number;
    title: string;
  };
  editProductReferenceList?: {
    id: number;
    title: string;
  }[];
  editProductVariantReference?: {
    id: number;
    title: string;
  };
  editProductVariantReferenceList?: {
    id: number;
    title: string;
  }[];
}

/**
 * Coda Row Interface for MetafieldDefinitions Sync Table
 */
export interface MetafieldDefinitionRow extends BaseRow {
  admin_url?: string;
  id: number;
  admin_graphql_api_id?: string;
  description?: string;
  key?: string;
  name: string;
  metafieldsCount?: number;
  namespace?: string;
  pinnedPosition?: number;
  type?: string;
  validations?: {
    name?: string;
    type?: string;
    value?: string;
  }[];
  validationStatus?: string;
  visibleToStorefrontApi?: boolean;
  ownerType?: string;
}

/**
 * Coda Row Interface for Metaobjects Sync Table
 */
export interface MetaobjectRow extends BaseRow {
  id: number;
  admin_graphql_api_id?: string;
  handle: string;
  updatedAt?: string | number | Date;
  admin_url?: string;
}

/**
 * Coda Row Interface for Orders Sync Table
 */
export interface OrderRow extends BaseRow {
  admin_url?: string;
  admin_graphql_api_id?: string;
  id: number;
  app_id?: number;
  billing_address?: {
    display?: string;
    address1?: string;
    address2?: string;
    city?: string;
    company?: string;
    country?: string;
    country_code?: string;
    country_name?: string;
    first_name?: string;
    last_name?: string;
    name?: string;
    latitude?: string;
    longitude?: string;
    phone?: string;
    province?: string;
    province_code?: string;
    zip?: string;
  };
  buyer_accepts_marketing?: boolean;
  cancel_reason?: string;
  cancelled_at?: string | number | Date;
  browser_ip?: string;
  browser_user_agent?: string;
  browser_accept_language?: string;
  closed_at?: string | number | Date;
  company?: {
    id: number;
    location_id?: number;
  };
  confirmation_number?: string;
  created_at?: string | number | Date;
  currency?: string;
  current_total_additional_fees?: number;
  current_total_discounts?: number;
  current_total_duties?: number;
  current_total_price?: number;
  current_subtotal_price?: number;
  current_total_tax?: number;
  customer?: {
    id: number;
    display: string;
  };
  customer_locale?: string;
  discount_applications?: {
    allocation_method?: string;
    amount?: number;
    code?: string;
    description?: string;
    target_selection?: string;
    target_type?: string;
    title?: string;
    type?: string;
    value?: number;
    value_type?: string;
  }[];
  discount_codes?: {
    amount?: number;
    code?: string;
    type?: string;
  }[];
  email?: string;
  estimated_taxes?: boolean;
  financial_status?: string;
  fulfillments?: {
    admin_graphql_api_id?: string;
    created_at?: string | number | Date;
    id: number;
    line_items?: {
      id: number;
      attributed_staffs?: {
        id?: string;
        quantity?: number;
      }[];
      custom?: boolean;
      fulfillable_quantity?: number;
      fulfillment_service?: string;
      fulfillment_status?: string;
      grams?: number;
      price?: number;
      product_id?: number;
      quantity?: number;
      requires_shipping?: boolean;
      sku?: string;
      title?: string;
      variant_id?: number;
      variant_title?: string;
      vendor?: string;
      name: string;
      gift_card?: boolean;
      properties?: {
        name?: string;
        value?: string;
      }[];
      taxable?: boolean;
      tax_lines?: {
        title?: string;
        price?: number;
        rate?: number;
        channel_liable?: boolean;
      }[];
      tip_payment_gateway?: string;
      tip_payment_method?: string;
      total_discount?: number;
      discount_allocations?: {
        amount?: number;
        discount_application_index?: number;
      }[];
      duties?: {
        id: number;
        tax_lines?: {
          title?: string;
          price?: number;
          rate?: number;
          channel_liable?: boolean;
        }[];
        country_code_of_origin?: string;
        harmonized_system_code?: string;
      }[];
      product_exists?: boolean;
      variant_inventory_management?: string;
    }[];
    location_id?: number;
    name?: string;
    notify_customer?: boolean;
    order_id?: number;
    origin_address?: {
      address1?: string;
      address2?: string;
      city?: string;
      country_code?: string;
      province_code?: string;
      zip?: string;
    };
    receipt?: {
      testcase?: boolean;
      authorization?: string;
    };
    service?: string;
    shipment_status?: string;
    status?: string;
    tracking_company?: string;
    tracking_numbers?: string[];
    tracking_number?: string;
    tracking_urls?: string[];
    tracking_url?: string;
    updated_at?: string | number | Date;
  }[];
  fulfillment_status?: string;
  landing_site?: string;
  line_items?: {
    id: number;
    attributed_staffs?: {
      id?: string;
      quantity?: number;
    }[];
    custom?: boolean;
    fulfillable_quantity?: number;
    fulfillment_service?: string;
    fulfillment_status?: string;
    grams?: number;
    price?: number;
    product_id?: number;
    quantity?: number;
    requires_shipping?: boolean;
    sku?: string;
    title?: string;
    variant_id?: number;
    variant_title?: string;
    vendor?: string;
    name: string;
    gift_card?: boolean;
    properties?: {
      name?: string;
      value?: string;
    }[];
    taxable?: boolean;
    tax_lines?: {
      title?: string;
      price?: number;
      rate?: number;
      channel_liable?: boolean;
    }[];
    tip_payment_gateway?: string;
    tip_payment_method?: string;
    total_discount?: number;
    discount_allocations?: {
      amount?: number;
      discount_application_index?: number;
    }[];
    duties?: {
      id: number;
      tax_lines?: {
        title?: string;
        price?: number;
        rate?: number;
        channel_liable?: boolean;
      }[];
      country_code_of_origin?: string;
      harmonized_system_code?: string;
    }[];
    product_exists?: boolean;
    variant_inventory_management?: string;
  }[];
  location_id?: number;
  merchant_of_record_app_id?: number;
  name: string;
  note?: string;
  note_attributes?: {
    name?: string;
    value?: string;
  }[];
  number?: number;
  order_number?: number;
  original_total_additional_fees?: number;
  original_total_duties?: number;
  payment_terms?: {
    amount?: number;
    currency?: string;
    payment_terms_name?: string;
    payment_terms_type?: string;
    due_in_days?: number;
    payment_schedules?: {
      amount?: number;
      currency?: string;
      issued_at?: string | number | Date;
      due_at?: string | number | Date;
      completed_at?: string | number | Date;
      expected_payment_method?: string;
    }[];
  };
  payment_gateway_names?: string[];
  phone?: string;
  po_number?: string;
  presentment_currency?: string;
  processed_at?: string | number | Date;
  referring_site?: string;
  refunds?: {
    id: number;
    created_at?: string | number | Date;
    duties?: {
      id: number;
      tax_lines?: {
        title?: string;
        price?: number;
        rate?: number;
        channel_liable?: boolean;
      }[];
      country_code_of_origin?: string;
      harmonized_system_code?: string;
    }[];
    note?: string;
    order_adjustments?: {
      id: number;
      order_id?: number;
      refund_id?: number;
      kind?: string;
      reason?: string;
      amount?: number;
      tax_amount?: number;
    }[];
    processed_at?: string | number | Date;
    refund_duties?: {
      duty_id?: number;
      refund_type?: string;
    }[];
    refund_line_items?: {
      id: number;
      line_item_id?: number;
      quantity?: number;
      restock_type?: string;
      location_id?: number;
      subtotal?: number;
      total_tax?: number;
    }[];
    transactions?: {
      id: number;
      label: string;
      amount?: number;
      currency?: string;
      createdAt?: string | number | Date;
      errorCode?: string;
      gateway?: string;
      kind?: string;
      parentTransactionId?: number;
      paymentId?: string;
      processedAt?: string | number | Date;
      status?: string;
      test?: boolean;
      totalUnsettled?: number;
    }[];
    user_id?: number;
  }[];
  shipping_address?: {
    display?: string;
    address1?: string;
    address2?: string;
    city?: string;
    company?: string;
    country?: string;
    country_code?: string;
    country_name?: string;
    first_name?: string;
    last_name?: string;
    name?: string;
    latitude?: string;
    longitude?: string;
    phone?: string;
    province?: string;
    province_code?: string;
    zip?: string;
  };
  shipping_lines?: {
    id: number;
    code?: string;
    discounted_price?: number;
    price?: number;
    source?: string;
    title?: string;
    tax_lines?: {
      title?: string;
      price?: number;
      rate?: number;
      channel_liable?: boolean;
    }[];
    carrier_identifier?: string;
    requested_fulfillment_service_id?: string;
  }[];
  source_name?: string;
  source_identifier?: string;
  source_url?: string;
  subtotal_price?: number;
  tags?: string;
  tax_lines?: {
    title?: string;
    price?: number;
    rate?: number;
    channel_liable?: boolean;
  }[];
  taxes_included?: boolean;
  test?: boolean;
  total_discounts?: number;
  total_line_items_price?: number;
  total_outstanding?: number;
  total_price?: number;
  total_shipping_price?: number;
  total_tax?: number;
  total_tip_received?: number;
  total_weight?: number;
  updated_at?: string | number | Date;
  user_id?: number;
  order_status_url?: string;
  confirmed?: boolean;
}

/**
 * Coda Row Interface for OrderLineItems Sync Table
 */
export interface OrderLineItemRow extends BaseRow {
  id: number;
  attributed_staffs?: {
    id?: string;
    quantity?: number;
  }[];
  custom?: boolean;
  fulfillable_quantity?: number;
  fulfillment_service?: string;
  fulfillment_status?: string;
  grams?: number;
  price?: number;
  product_id?: number;
  quantity?: number;
  requires_shipping?: boolean;
  sku?: string;
  title?: string;
  variant_id?: number;
  variant_title?: string;
  vendor?: string;
  name: string;
  gift_card?: boolean;
  properties?: {
    name?: string;
    value?: string;
  }[];
  taxable?: boolean;
  tax_lines?: {
    title?: string;
    price?: number;
    rate?: number;
    channel_liable?: boolean;
  }[];
  tip_payment_gateway?: string;
  tip_payment_method?: string;
  total_discount?: number;
  discount_allocations?: {
    amount?: number;
    discount_application_index?: number;
  }[];
  duties?: {
    id: number;
    tax_lines?: {
      title?: string;
      price?: number;
      rate?: number;
      channel_liable?: boolean;
    }[];
    country_code_of_origin?: string;
    harmonized_system_code?: string;
  }[];
  product_exists?: boolean;
  variant_inventory_management?: string;
  order_id?: number;
  order?: {
    id: number;
    name: string;
  };
  variant?: {
    id: number;
    title: string;
  };
  admin_graphql_api_id?: string;
}

/**
 * Coda Row Interface for OrderTransactions Sync Table
 */
export interface OrderTransactionRow extends BaseRow {
  id: number;
  label: string;
  amount?: number;
  currency?: string;
  createdAt?: string | number | Date;
  errorCode?: string;
  gateway?: string;
  kind?: string;
  parentTransactionId?: number;
  paymentId?: string;
  processedAt?: string | number | Date;
  status?: string;
  test?: boolean;
  totalUnsettled?: number;
  accountNumber?: string;
  authorizationCode?: string;
  authorizationExpiresAt?: string | number | Date;
  order?: {
    id: number;
    name: string;
  };
  orderId?: number;
  parentTransaction?: {
    id: number;
    label: string;
  };
  paymentDetails?: {
    avsResultCode?: string;
    bin?: string;
    company?: string;
    cvvResultCode?: string;
    expirationMonth?: number;
    expirationYear?: number;
    name?: string;
    number?: string;
    paymentMethodName?: string;
    wallet?: string;
  };
  paymentIcon?: string;
  receiptJson?: string;
  settlementCurrency?: string;
  settlementCurrencyRate?: number;
}

/**
 * Coda Row Interface for Pages Sync Table
 */
export interface PageRow extends BaseRow {
  admin_url?: string;
  shop_url?: string;
  admin_graphql_api_id?: string;
  id: number;
  body?: string;
  body_html?: string;
  handle?: string;
  author?: string;
  title: string;
  template_suffix?: string;
  created_at?: string | number | Date;
  updated_at?: string | number | Date;
  published?: boolean;
  published_at?: string | number | Date;
}

/**
 * Coda Row Interface for Products Sync Table
 */
export interface ProductRow extends BaseRow {
  admin_url?: string;
  storeUrl?: string;
  id: number;
  admin_graphql_api_id?: string;
  body?: string;
  body_html?: string;
  created_at?: string | number | Date;
  handle?: string;
  images?: string[];
  featuredImage?: string;
  options?: string;
  product_type?: string;
  published_at?: string | number | Date;
  published_scope?: string;
  status?: string;
  tags?: string;
  template_suffix?: string;
  title: string;
  updated_at?: string | number | Date;
  vendor?: string;
}

/**
 * Coda Row Interface for ProductVariants Sync Table
 */
export interface ProductVariantRow extends BaseRow {
  admin_url?: string;
  storeUrl?: string;
  admin_graphql_api_id?: string;
  barcode?: string;
  compare_at_price?: number;
  created_at?: string | number | Date;
  grams?: number;
  id: number;
  image?: string;
  inventory_item_id?: number;
  inventory_management?: string;
  inventory_policy?: string;
  inventory_quantity?: number;
  option1?: string;
  option2?: string;
  option3?: string;
  price?: number;
  position?: number;
  product?: {
    id: number;
    title: string;
  };
  sku?: string;
  taxable?: boolean;
  tax_code?: string;
  title: string;
  displayTitle?: string;
  updated_at?: string | number | Date;
  weight?: number;
  weight_unit?: string;
}

/**
 * Coda Row Interface for Redirects Sync Table
 */
export interface RedirectRow extends BaseRow {
  admin_url?: string;
  test_url?: string;
  id: number;
  path?: string;
  target?: string;
}

/**
 * Coda Row Interface for Shops Sync Table
 */
export interface ShopRow extends BaseRow {
  id: number;
  name: string;
  address1?: string;
  address2?: string;
  checkout_api_supported?: boolean;
  city?: string;
  country_code?: string;
  country_name?: string;
  county_taxes?: boolean;
  created_at?: string | number | Date;
  customer_email?: string;
  currency?: string;
  domain?: string;
  enabled_presentment_currencies?: string[];
  eligible_for_payments?: boolean;
  email?: string;
  google_apps_domain?: string;
  has_discounts?: boolean;
  has_gift_cards?: boolean;
  has_storefront?: boolean;
  iana_timezone?: string;
  latitude?: number;
  longitude?: number;
  money_format?: string;
  money_in_emails_format?: string;
  money_with_currency_format?: string;
  money_with_currency_in_emails_format?: string;
  myshopify_domain?: string;
  password_enabled?: boolean;
  phone?: string;
  plan_display_name?: string;
  pre_launch_enabled?: boolean;
  plan_name?: string;
  primary_locale?: string;
  province?: string;
  province_code?: string;
  requires_extra_payments_agreement?: boolean;
  setup_required?: boolean;
  shop_owner?: string;
  source?: string;
  taxes_included?: boolean;
  timezone?: string;
  transactional_sms_disabled?: boolean;
  updated_at?: string | number | Date;
  weight_unit?: string;
  zip?: string;
  marketing_sms_consent_enabled_at_checkout?: boolean;
  admin_url?: string;
}
